; Super Mario Galaxy 2 VR - menu (B + Y). Index of the chosen value per option.
fp=1
camdist2=22
guide=1
camfwd3=28
eyeoff3=32
cull2=0
body=1
arms=1
glove=1
bodyscale=0
handfwd3=16
handup3=16
pitch=9
markers=0
fps3=0
movie=1
lumasnd=1
starsnd=1
music=0
yoshiup=3
foosteer=1
walk=1
snap=1
movefwd=0
farcull=3
